### PR TITLE
Add top level key to reply event to keep consistent with request format

### LINKED ISSUE #55: Update reply event structure to keep consistent with request event
More detail at: https://github.com/rancherio/cattle/issues/161

Basically we need to add top-level key to the reply event we transferred back, like:

InstanceHostMap: {Instance: { Volume {.. } .. } .. }

Rather than 

Instance: { Volume {.. } .. } ..

### PR DESCRIPTION
**Pull request by yasker**
Fixes #55

### CODE REVIEW

**Comment by yasker** [comment]
Need cattle server change: https://github.com/rancherio/cattle/pull/162

**Comment by yasker** [comment]
Several tests failed due to lack of server side change. Integration test passed on my local machine.

**Comment by ibuildthecloud** [comment]
@yasker python-agent tests are self contained and do not rely on cattle.  They should pass independently.

**Comment by ibuildthecloud** [comment]
It seems this fix should be at a higher level.  The methods changed are for creating a map representation of the object.  It doesn't seem right to return an object that has a single top level key.  I would instead change it at https://github.com/rancherio/python-agent/blob/master/cattle/agent/handler.py#L80.  You will need to change that code to have reference to the req obj as that is where the type is.

**Comment by yasker** [comment]
@ibuildthecloud Sorry, forgot the python-agent tests. Would update as well.

**Pull request closed without merging**
