### PR TITLE
Make container state file write atomic

### PR DESCRIPTION
**Pull request by cjellick**
Addresses a bug where host-api would attempt to unmarshall the
container json before it was fully written.

### CODE REVIEW

**Comment by alena1108** [comment]
LGTM as long as we lock operations on per-container basis; otherwise there is a possibility of clashing remove/renames of temp file.

**Comment by cjellick** [comment]
Going to tweak locking per alena's comment, so don't merge.

**Comment by cjellick** [comment]
@alena1108 @son I updated so that `_record_rancher_container_state` is always called inside of a lock

**Comment by alena1108** [comment]
LGTM

**Comment by sonchang** [comment]
LGTM

**Comment by sonchang** [comment]
Will wait until drone build completes before merging

**Pull request merged**
