### PR TITLE
Add top level key to reply event to keep consistent with request format

### LINKED ISSUE #55: Update reply event structure to keep consistent with request event
More detail at: https://github.com/rancherio/cattle/issues/161

Basically we need to add top-level key to the reply event we transferred back, like:

InstanceHostMap: {Instance: { Volume {.. } .. } .. }

Rather than 

Instance: { Volume {.. } .. } ..

### PR DESCRIPTION
**Pull request by yasker**
Fixes #55. Also updated all the test cases.

This also fixed the wrongly marked resourceType of mocked requests.

### CODE REVIEW

**Comment by yasker** [comment]
OK, flake8...

Any coding style suggestion to break something like this into multiple lines?

>        del resp['data']['imageStoragePoolMap']['+data']['dockerImage']['VirtualSize']

**Comment by ibuildthecloud** [comment]
A backslash to break the line is fine.  Or assign one of the inner maps to a variable.

**Comment by ibuildthecloud** [comment]
This looks good but I'm going to hold off on merging this until github phase 1 is done.  The size of the change in python-agent has gotten quite large (not this PR but the ones before).  I want to wait until cattle picks up current master.

**Comment by yasker** [comment]
Sure. Thanks!

**Comment by ibuildthecloud** [comment]
@yasker Sorry, but breaking changes are tricky to push out.  I'm dealing with this right now with some of the github work.  What I'd prefer is that we do a lock step approach.

1. Release python-agent that supports both old and new behavior
2. Create a PR to remove legacy behavior
3. Include python-agent in cattle with cattle also moving to the new behavior
4. Merge python-agent PR to master to remove legacy behavior
5. Include new python-agent in cattle

If we do this this way cattle master and python master will always work together.  I know it's more work, but that's just the problem with breaking changes.

**Comment by yasker** [comment]
@ibuildthecloud The related modification is much more in python-agent side(mostly on test cases) compared to cattle server, but not so much on cattle server, so how about this:

1. A cattle server PR for both old and new behavior. Then this can be merged without breaking anything.
2. Python agent PR stay the same, after cattle is merged, it won't break cattle.
3. After python-agent merged, submit another PR to remove backward compatibility.

**Comment by yasker** [comment]
@ibuildthecloud Thanks Darren! I would send out PR for removing temporary compatibility code today.

**Pull request merged**
