### PR TITLE
Make tests fail at flake8 or on first test failed.

### PR DESCRIPTION
**Pull request by hibooboo2**

### CODE REVIEW

**Comment by cjellick** [comment]
LGTM. @ibuildthecloud any input? Are you good with failing the build on the first failed test?

**Comment by ibuildthecloud** [comment]
I like running flake8 first, but wouldn't you want to know if your tests pass/fail regardless of flake8?

I thought flake8 ran first already.

**Comment by ibuildthecloud** [comment]
I guess it's useful to fail fast if you're not watching the log

LGTM

**Comment by cjellick** [comment]
I believe it ran first, but didn't report the failure and fail the build until all of tox was completed.

**Pull request merged**
